version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    build:      
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped    
    ports:
       - "8001:80"

  autorizador:
    build: autorizador
    volumes:
      - ./autorizador:/autorizador
    ports:
      - 5010:5000
    depends_on:
      - nginx