version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    build:      
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped    
    ports:
       - "8001:80"