version: '3'

services:

  autorizador:
    build: autorizador
    volumes:
      - ./autorizador:/app
    ports:
      - 5010:5000

  registro:
    build: registro
    volumes:
      - ./registro:/app
    ports:
      - 5011:5000
      
  historiaclinica:
    build: historiaclinica
    volumes:
      - ./historiaclinica:/app
    ports:
      - 5012:5000
