version: '3'

services:

  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/index.html:/app/html:ro
  

  reportes:
    build: reportes
    volumes:
      - ./reportes:/app

  reportesdos:
    build: reportesdos
    volumes:
      - ./reportesdos:/app

  auth:
    build: auth
    volumes:
      - ./auth:/app
    ports:
      - 5001:5000

  historiaclinica:
    build: historiaclinica
    volumes:
      - ./historiaclinica:/app
    ports:
      - 5002:5000

  registro:
    build: registro
    volumes:
      - ./registro:/app
    ports:
      - 5002:5000